### ISSUE TITLE
Logo Proposal: BallTale

### ISSUE THREAD

**Issue by baranpirincal** [SiiMeR/BallTale#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by SiiMeR** [comment]
Hi

That would be really nice if you designed a logo. Looking forward to it :)

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
Hello!

[[Here is my first experiment]](http://i.hizliresim.com/1EvpBb.jpg)

I am not totally sure about this, we can add or remove something on design. I am waiting your suggestions,ideas and comments.

Best Regards

Baran Pirinçal

**Comment by baranpirincal** [comment]
@SiiMeR 

Hey again,

I think we can talk about on that. will we just show the ball or add something?

![ball22wwe4](https://user-images.githubusercontent.com/37786733/42170742-119f036e-7e20-11e8-8fda-b2d2ab082cb5.jpg)

Best Regards

Baran Pirinçal

**Comment by SiiMeR** [comment]
Hi

Hmm, the ones in the center column look nice, the others feel to 3D. Maybe add a more accented outline to make the logo resemble the ball in the game?   

https://github.com/SiiMeR/BallTale/blob/master/Assets/Sprites/ball.png  

And what about making the grid effect less pronounced? What do you think about these changes and what direction would you take this logo in?

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
@SiiMeR 

Hey!

![11](https://user-images.githubusercontent.com/37786733/42219186-b4f634c0-7ed3-11e8-9af9-9d36fa04f425.jpg)

Best Regards
Baran Pirinçal

**Comment by SiiMeR** [comment]
Hey

The ones in the top row look great. Really loving it. That text in the bottom looks cool, but maybe you could apply grid to the text too? And then combine them into 1 so it reads : BALL o TALE, where the o symbol is the logo itself :D 
What do you think of this? We can try to pursue other directions too if you have any ideas. 

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
@SiiMeR 

Hey agian,

I think combining text and icon is possible and good idea. 

I made grid lines on letters as you wish and in my opinion it became better :)

Also, i am still ready if you want to change something! :)

Best Regards
Baran Pirinçal

![xx](https://user-images.githubusercontent.com/37786733/42243998-d87bab9e-7f1b-11e8-9713-e633abf17fbb.jpg)


![cover](https://user-images.githubusercontent.com/37786733/42243852-5ab2adb6-7f1b-11e8-8720-2cb998bc3095.jpg)

**Comment by SiiMeR** [comment]
Hey

This looks great. Maybe now you could try making different variations of the logo (left side text green and right side text red, left fraction of ball red and right fraction of ball green instead and so on. I hope you get the idea). You can also try playing with spacings and text size vs logo size. In my opinion, this logo is nearing its final form, just need a little bit of tweaking.

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
@SiiMeR 

Hey,

I will try different variations and size variations of logo design tonight.

Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
@SiiMeR 

![sonsonball](https://user-images.githubusercontent.com/37786733/42288974-c651471c-7fc5-11e8-9e48-e136f3a9bff7.jpg)

**Comment by SiiMeR** [comment]
Hey

I can't make up my mind choosing between these designs :D . Could you maybe do one where the ball is completely green and the text is bigger than the ball? I would like to see how that feels.

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
@SiiMeR 

Here,

![90](https://user-images.githubusercontent.com/37786733/42291999-009f46c8-7fd8-11e8-95a2-9b3558b751d7.jpg)

**Comment by SiiMeR** [comment]
Hey

I think these last ones don't look so great at all. The previous felt like they would go with the game much better. The 6th from the top (from the post before your last post) looks and feels the best out of them all.

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
Hey,

I'm making last arrangements, which size do you need for full logo and ball icon?

Best Regards
Baran Pirinçal

**Comment by SiiMeR** [comment]
Hey

What do you mean by size?

Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
I mean resolution 64x64 - 128x128 px or something like that or I can upload high quality .PNG and .PDF version of logo design.

Best Regards
Baran Pirinçal

**Comment by SiiMeR** [comment]
High quality version is fine

Regards
Siim Raudsepp

**Comment by SiiMeR** [comment]
Hey

Wanted to say thanks to you for doing this. It was certainly interesting working with you.

Best Regards
Siim Raudsepp

**Comment by baranpirincal** [comment]
@SiiMeR 

You're welcome, feel free to contact me if you need something in the graphic field.

Good luck

Best Regards
Baran Pirinçal
